repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
  - repo: local
    hooks:
      - id: isort
        name: Sort imports
        entry: isort
        args: ["."]
        language: system
        types:
          - python
      - id: black
        name: Format codes
        entry: black
        args: [--safe]
        language: system
        types:
          - python
      - id: codespell
        name: Fix typos
        args: [-w]
        entry: codespell
        language: system
